defailt:info
info:

generate_refferences:
	python3.9 -m eff_word_net.generate_reference \
       	--input-dir=./audio-custom \
	--output-dir=./out \
	--wakeword="rosko" \
	--model-type="resnet_50_arc" 

